### ISSUE TITLE
Improve: configurable table/function/trigger prefix

### ISSUE THREAD

**Issue by gustapinto** [gustapinto/from-to#4]
Today the application uses "from_to*" as an prefix for the tables, functions and triggers it creates, but it will be good to provide and optional to configure this prefix, with "from_to*" working as the default value or "fallback"

Example config:
```yaml
input:
  connector: "postgres"
  postgresConfig:
    dsn: "postgres://from-to-user:from-to-passw@localhost:5432/from-to-db?sslmode=disable"
    pollSeconds: 10
    schemaPrefix: "customPrefixForSchema"
    schemaPrefixSeparator: "-" # Used to separate the input.postgresConfig.schemaPrefix from the table or function name
    tables:
      - "sales"
```
